#!/usr/bin/env bash
# Fix a web_server to run Nginx as the nginx user listening on port 8080.

# set a user in the config by cp '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# cp port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give permissions_access to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill the process if it is running
pkill apache2
# now start the nginx service with the new nginx users
sudo -u nginx service nginx start
